name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        python -m unittest

    - name: Deploy to Surge
      run: |
        surge --project ./ --domain finall2.surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
